### ISSUE TITLE
Unclear how to implement theme

### ISSUE THREAD

**Issue by diplodata** [BesrourMS/dimension#2]
I'm not sure how the user is supposed to implement this (very nice looking) theme.  The root `index.md` file bears no resemblance to the demo page.  What am I missing?

I have managed to install and apply it to a page.  But based on this documentation I have no idea how to tailor it to my content.

**Comment by bmen** [comment]
the same with me. How can I create multiple pages that can be scrolled horizontally?

**Comment by BesrourMS** [comment]
Just duplicate the intro.md file

**Comment by diplodata** [comment]
Thanks for a speedy response!
