### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by ikilledroundhead** [BesrourMS/dimension#4]
I was hoping you could help point me in the right direction on how to add my own logo the correct way. I want my logo to load just as yours does in your demo but I can’t figure out where to place the code in my pages. I see your css for it but I’m lost where to place my code... thank you in advance!

**Comment by BesrourMS** [comment]
Hi @ikilledroundhead 
In the default theme, you should add a font awesome icon so if you want to add your logo go to line 19 in the index.twig and replace the span tag by an IMG tag, don't forget to update index.md with an URL for your logo
