### ISSUE TITLE
Current theme "dimension" uses API version 0, but Pico provides API version 3

### ISSUE THREAD

**Issue by TwizzyDizzy** [BesrourMS/dimension#5]
Hey there,

I followed the instructions in README.md, yet I get the error:

`[Wed May 06 01:08:29.448681 2020] [proxy_fcgi:error] [pid 5443:tid 139621809129216] [client 91.64.245.59:60415] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RuntimeException: Current theme "dimension" uses API version 0, but Pico provides API version 3 and PicoDeprecated isn't loaded in /var/www/html/lib/Pico.php:1144\nStack trace:\n#0 /var/www/html/lib/Pico.php(441): Pico->loadTheme()\n#1 /var/www/html/index.php(40): Pico->run()\n#2 {main}\n  thrown in /var/www/html/lib/Pico.php on line 1144'`

* `git clone picocms v2.1.2`
* `git clone https://github.com/BesrourMS/dimension.git` and then move it to themes folder
* copy your `index.md` to `content`
* `theme: dimension` in `config.yml`

Any clue as to what causes this?

Running this on PHP (FPM) 7.3.

Also not sure whether it makes more sense to post this to the picocms github repo.

Thanks for any input you want to provide! :)

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Ah sorry... no... this also happens with the standard theme. Probably this error is not up your alley.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
After investigating a bit more, your theme seems to be lacking the now required `pico-theme.yml` file.

Creating it with (for example and without knowing if this is correct) the following content (borrowed from the official pico theme) it works:

```
api_version: 3                  # Use Pico's latest API version for themes

meta:                           # Register meta headers used by this theme
    Logo: logo                  # The URL to your website's logo (value is passed to Pico's "url" Twig filter)
    Tagline: tagline            # Your website's tag line, shown right below your site title (supports Markdown)
    Social: social              # A list of social icons that will be shown in your website's footer;
                                #     You must specify a "title", "url" and "icon" per entry

twig_config:                    # Twig template engine config
    autoescape: html            # Let Twig escape variables by default
    strict_variables: false     # If set to true, Twig will bail out when unset variables are being used
    charset: utf-8              # The charset used by Twig templates

widescreen: false               # Use more horicontal space (i.e. make the site container wider)
```

**Comment by BesrourMS** [comment]
Hi @TwizzyDizzy, 
You can just create a config.yml in config folder and change theme in the line 14, it works great without pico-theme.yml

**Comment by BesrourMS** [comment]
@TwizzyDizzy I test dimension with the latest version of Pico CMS 2.1.2, It works fine for me.
