### ISSUE TITLE
How can we change the pages contents?

### ISSUE THREAD

**Issue by gelavat** [BesrourMS/dimension#9]
I like this theme very much, it is nice looking.
However there is missing documentation on how to edit the texts on the pages.

I managed to implement it on a web server. I could change the background image by replacing the "pico/themes/dimension/images/bg.jpg" file.
Also I could change the main displayed text on the first page in capital letters from the "pico/content/index.md" file.

However by default there is only the "contact" page. How can I add the "intro" page and contents please?

Looking at the index.twig file, it seems that there is a list of pages that we need to format somewhere. Can you please provide an example, or your full index.md file? Because the one on github by default only has 10 lines of code, and these pages are not listed there.

Thanks if you can help.

**Comment by gelavat** [comment]
You are welcome.
Can you please answer my request: How to add contents?

**Comment by BesrourMS** [comment]
Hi @gelavat, try to copy intro.md and just change nav meta

**Comment by gelavat** [comment]
Thank you very much, I managed to add new pages, it is working fine now!
It will need some doc to explain it.

Also, how can I change the top globe icon?
And how can we change the contact form, I don't see the "contact.md" page. Also to change its social icons and the destination e-mail address of the form when sending?

Thanks

**Comment by BesrourMS** [comment]
Hi @gelavat 
for the icon, social links and the email destination just change the index.md
for the contact page you should make the modifications directely in index.twig

**Comment by gelavat** [comment]
Thank you this helps a bit already.
But for the icon, I need to know the list of possible icon names that I can put in the index.md file. Currently it is 'globe', but what other icons are available, or where is the file located?

Also on the provided index.md file on github, there is no example with an e-mail address for the contact form. Can you please provide one?

**Comment by mayamcdougall** [comment]
The icons are provided by Font Awesome, a fairly common icon set used in web development (and especially prevalent in Pico themes).  The icons included here are a bit older now, but you can [Search](https://fontawesome.com/v4.7/icons/) through the older version or use its [Cheatsheet](https://fontawesome.com/v4.7/cheatsheet/) to find the icon you want.  It might involve some trial and error if a particular icon is included or not (those resources are for `v4.7`, the last release of the `4.0` branch, while this theme only includes `v4.6.3`).

Also, I believe the contact form here relies on having an external setup on your sever to process the HTTP Post data from the form.  It's a bit of an advanced topic (anything regarding the sending or receiving of emails is).  I know there are some "simple" PHP email sending scripts out there that you could tie into it (I've used them before), but it's far from an easy thing to set up and definitely outside of my expertise.

---

(@BesrourMS, Hello from the Pico project. 👋🏻)

**Comment by gelavat** [comment]
Thank you very much for this information about Font Awesone. Also for the icons, exactly what I needed to be able to update and put the proper icon, great!
For the contact form it seems more complicated that's true. I will have to dig into that a bit more.

I will try to provide an updated installation instruction and customization section as a PR to be able to close the ticket, with all that summarized there.
